export interface Mechanism {
  num: number
  moduleId: string
  group: string
  title: string
  owner: string
  what: string
  gain: string
  visual: string
  color: string
  status: string
  before: string
  after: string
}

export const MECHANISMS: Mechanism[] = [
  {
    num: 1,
    moduleId: 'semantic-routing',
    group: 'per-record',
    title: 'vLLM Semantic Router',
    owner: 'Red Hat · vLLM',
    what: 'Embedding-based classification routes each request to the right-sized model in <1ms (after embedding model warm-up)',
    gain: 'Simple tasks use 2B model (fast). Complex tasks use 3.8B model (accurate). Avoids wasting large model capacity on classification tasks.',
    visual: 'router',
    color: 'var(--rh-red)',
    status: 'live',
    before: '1 model for everything',
    after: 'Right model per task — 40% less compute on simple workloads',
  },
  {
    num: 2,
    moduleId: 'conditional-pipeline',
    group: 'per-record',
    title: 'Conditional Pipeline',
    owner: 'LangGraph',
    what: 'Skips inference steps that aren\'t needed for the current record',
    gain: 'If <2 medications found, the drug interaction check is skipped entirely. No inference call, no latency, no compute. The pipeline adapts per record.',
    visual: 'pipeline',
    color: 'var(--accent-blue)',
    status: 'live',
    before: '4 inference calls per record (always)',
    after: '2-4 calls per record (adaptive) — fewer calls on average (workload-dependent)',
  },
  {
    num: 3,
    moduleId: 'mcp-tools',
    group: 'per-record',
    title: 'MCP Tools (Data, Not LLM)',
    owner: 'Red Hat · MCP Gateway',
    what: 'Drug interactions come from a curated database via MCP, not an LLM call',
    gain: 'The FDA drug interaction lookup takes 16ms. An LLM call to answer the same question takes 3-8 seconds. Not everything needs inference.',
    visual: 'tools',
    color: 'var(--rh-teal)',
    status: 'live',
    before: 'LLM call for drug data: ~4s',
    after: 'Database lookup via MCP: 16ms — 250x faster',
  },
  {
    num: 4,
    moduleId: 'model-optimization',
    group: 'model',
    title: 'Model Optimization',
    owner: 'Intel · AMX',
    what: 'Same hardware, better inference — four independent levers that compound',
    gain: 'Each optimization reduces latency independently. Apply one or all. The gains stack on the same $0/token hardware — no new procurement, no GPU, just better engineering.',
    visual: 'modelopt',
    color: 'var(--intel-cyan)',
    status: 'options',
    before: 'Unoptimized FP32 model: ~8s/record',
    after: 'Optimized + quantized: projected 2-4x faster on same CPU',
  },
  {
    num: 5,
    moduleId: 'batch-processing',
    group: 'fleet',
    title: 'AMQ Streams Batch Processing',
    owner: 'Red Hat',
    what: 'Async event streaming processes thousands of records in parallel',
    gain: 'Instead of synchronous one-at-a-time API calls, records stream through topics and process concurrently. Throughput scales with consumers.',
    visual: 'streams',
    color: 'var(--rh-orange)',
    status: 'live',
    before: 'Sequential API: 1 record at a time',
    after: 'Event streaming: N records in parallel, same hardware',
  },
  {
    num: 6,
    moduleId: 'replica-scaling',
    group: 'fleet',
    title: 'Agent + Model Replica Scaling',
    owner: 'Red Hat · OpenShift',
    what: 'Scale agent pods AND model serving replicas independently on existing hardware',
    gain: 'Agent replicas reduce agent-side contention (~20-30% latency improvement). Model serving replicas (multiple vLLM workers) are where throughput scales linearly. Both scale on CPUs already in the fleet.',
    visual: 'replicas',
    color: 'var(--rh-blue)',
    status: 'tested',
    before: '1 agent → 1 vLLM worker: bottleneck',
    after: '3 agents → 3 vLLM workers: 3x throughput, same latency',
  },
  {
    num: 7,
    moduleId: 'llmd-inference',
    group: 'fleet',
    title: 'llm-d Disaggregated Inference',
    owner: 'Red Hat · llm-d',
    what: 'SLO-based scheduler separates prefill and decode across specialized nodes',
    gain: 'The llm-d planner routes inference based on latency SLO targets and available capacity. Prefill (compute-heavy) goes to high-core nodes. Decode (memory-bound) goes to memory-optimized nodes. Each node does what it\'s best at.',
    visual: 'llmd',
    color: 'var(--rh-purple)',
    status: 'roadmap',
    before: 'One node does everything: prefill + decode + queue',
    after: 'Specialized nodes: prefill node → decode node, SLO-aware routing',
  },
  {
    num: 8,
    moduleId: 'adaptive-classification',
    group: 'learning',
    title: 'Adaptive Classification',
    owner: 'LangGraph · Triforce',
    what: 'Unlike the 7 levers above, this one isn\'t a switch — it\'s a trajectory. The system caches every LLM classification result. On re-encounter, it returns the cached answer in <1ms. The more records it processes, the fewer LLM calls it needs.',
    gain: 'Day 1: every classification calls the LLM. As volume grows, the system is projected to reach ~60% cache hit rate within weeks, and ~95% over time. It teaches itself what it\'s already seen — and reserves inference capacity for documents it hasn\'t. Only possible at $0/token — cloud APIs give no incentive to cache.',
    visual: 'adaptive',
    color: 'var(--rh-green)',
    status: 'live',
    before: 'Every record calls the LLM for classification',
    after: 'Volume-dependent: projected to reach ~95% cached after warmup — cost per record drops with scale',
  },
  {
    num: 9,
    moduleId: 'speculative',
    group: 'fleet',
    title: 'Speculative Decoding',
    owner: 'vLLM · Intel',
    what: 'A small draft model proposes tokens ahead. The target model verifies them in a single pass. Correct tokens are accepted; wrong ones are regenerated. The demo reports measured latency for the active Oberon deployment.',
    gain: 'Works through vLLM and LiteLLM as a serving-layer optimization. If a prompt does not speed up, the UI says configured and measured instead of claiming a fixed multiplier.',
    visual: 'speculative',
    color: 'var(--intel-blue)',
    status: 'live',
    before: 'Generate tokens one at a time: each waits for the last',
    after: 'Draft proposes 5 tokens; target verifies in 1 pass; result is measured live',
  },
  {
    num: 10,
    moduleId: 'heterogeneous',
    group: 'fleet',
    title: 'Heterogeneous Compute Routing',
    owner: 'Red Hat · vLLM',
    what: 'The semantic router classifies each request by complexity and routes to the configured hardware tier. Simple requests stay on CPU. Complex requests use the Helm-configured complex model.',
    gain: 'Classification and NER stay on CPU when the router says they fit. Summarization and reasoning can route to the complex tier, with measured latency and quality deciding whether the extra compute is worth it.',
    visual: 'heterogeneous',
    color: 'var(--gpu-amber)',
    status: 'live',
    before: 'One hardware tier for everything: CPU or GPU, pick one',
    after: 'SIMPLE → CPU ($0) · COMPLEX → GPU ($/token) — routed automatically',
  },
  {
    num: 11,
    moduleId: 'fusion',
    group: 'learning',
    title: 'Multi-Model Fusion',
    owner: 'LangGraph · Triforce',
    what: 'For critical decisions, send the same question to 3 models in parallel. A judge model compares their responses: consensus, contradictions, blind spots. Cost: 4x one call. Value: confidence for decisions with consequences.',
    gain: 'Single model: one perspective, one set of blind spots. Panel of 3 + judge: consensus validated, contradictions caught, gaps identified. On CPU at $0/token, the extra calls are literally free.',
    visual: 'fusion',
    color: 'var(--accent-blue)',
    status: 'live',
    before: 'One model, one answer — hope it\'s right',
    after: '3 models + judge → consensus synthesis — confidence for critical decisions',
  },
  {
    num: 12,
    moduleId: 'benchmarking',
    group: 'analysis',
    title: 'Model Benchmarking',
    owner: 'guidellm · Triforce',
    what: 'Compare any model on any task on any hardware with real metrics. Latency, throughput, TTFT, quality — measured, not estimated. guidellm runs production-grade load sweeps.',
    gain: 'Every optimization claim is testable. Run the benchmark yourself — the numbers are live from MAAS, not slides.',
    visual: 'benchmark',
    color: 'var(--rh-teal)',
    status: 'live',
    before: 'Trust vendor benchmarks on different hardware',
    after: 'Run your own benchmarks on YOUR models, YOUR tasks, YOUR hardware',
  },
]
